//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations 3.2.
//


package com.jayqqaa12.reader.ui;

import android.content.Context;
import android.os.Bundle;
import android.os.Handler;
import android.os.Looper;
import android.support.v4.app.Fragment;
import android.view.View;
import android.view.View.OnClickListener;
import android.widget.AdapterView;
import android.widget.AdapterView.OnItemClickListener;
import android.widget.ImageView;
import android.widget.ListView;
import android.widget.ProgressBar;
import android.widget.TextView;
import com.jayqqaa12.reader.R.layout;
import com.jayqqaa12.reader.engine.TocEngine_;
import com.jayqqaa12.reader.model.db.Toc;
import org.androidannotations.api.builder.ActivityIntentBuilder;
import org.androidannotations.api.view.HasViews;
import org.androidannotations.api.view.OnViewChangedListener;
import org.androidannotations.api.view.OnViewChangedNotifier;

public final class TocActivity_
    extends TocActivity
    implements HasViews, OnViewChangedListener
{

    private final OnViewChangedNotifier onViewChangedNotifier_ = new OnViewChangedNotifier();
    private Handler handler_ = new Handler(Looper.getMainLooper());

    @Override
    public void onCreate(Bundle savedInstanceState) {
        OnViewChangedNotifier previousNotifier = OnViewChangedNotifier.replaceNotifier(onViewChangedNotifier_);
        init_(savedInstanceState);
        super.onCreate(savedInstanceState);
        OnViewChangedNotifier.replaceNotifier(previousNotifier);
        setContentView(layout.activity_toc);
    }

    private void init_(Bundle savedInstanceState) {
        OnViewChangedNotifier.registerOnViewChangedListener(this);
        getWindow().setFlags(android.view.WindowManager.LayoutParams.FLAG_FULLSCREEN, android.view.WindowManager.LayoutParams.FLAG_FULLSCREEN);
        engine = TocEngine_.getInstance_(this);
    }

    @Override
    public void setContentView(int layoutResID) {
        super.setContentView(layoutResID);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    @Override
    public void setContentView(View view, android.view.ViewGroup.LayoutParams params) {
        super.setContentView(view, params);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    @Override
    public void setContentView(View view) {
        super.setContentView(view);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    public static TocActivity_.IntentBuilder_ intent(Context context) {
        return new TocActivity_.IntentBuilder_(context);
    }

    public static TocActivity_.IntentBuilder_ intent(Fragment supportFragment) {
        return new TocActivity_.IntentBuilder_(supportFragment);
    }

    @Override
    public void onViewChanged(HasViews hasViews) {
        tv_head_logo = ((TextView) hasViews.findViewById(com.jayqqaa12.reader.R.id.tv_head_logo));
        tv_head = ((TextView) hasViews.findViewById(com.jayqqaa12.reader.R.id.tv_head));
        iv_head_right = ((ImageView) hasViews.findViewById(com.jayqqaa12.reader.R.id.iv_head_right));
        iv_head_left = ((ImageView) hasViews.findViewById(com.jayqqaa12.reader.R.id.iv_head_left));
        pb = ((ProgressBar) hasViews.findViewById(com.jayqqaa12.reader.R.id.pb));
        lv = ((ListView) hasViews.findViewById(com.jayqqaa12.reader.R.id.lv));
        if (iv_head_left!= null) {
            iv_head_left.setOnClickListener(new OnClickListener() {


                @Override
                public void onClick(View view) {
                    TocActivity_.this.iv_head_leftClicked(view);
                }

            }
            );
        }
        if (lv!= null) {
            lv.setOnItemClickListener(new OnItemClickListener() {


                @Override
                public void onItemClick(AdapterView<?> parent, View view, int position, long id) {
                    TocActivity_.this.lvItemClicked(((Toc) parent.getAdapter().getItem(position)));
                }

            }
            );
        }
        init();
    }

    @Override
    public void onLoadStatus(final Object obj, final int status) {
        handler_.post(new Runnable() {


            @Override
            public void run() {
                TocActivity_.super.onLoadStatus(obj, status);
            }

        }
        );
    }

    public static class IntentBuilder_
        extends ActivityIntentBuilder<TocActivity_.IntentBuilder_>
    {

        private Fragment fragmentSupport_;

        public IntentBuilder_(Context context) {
            super(context, TocActivity_.class);
        }

        public IntentBuilder_(Fragment fragment) {
            super(fragment.getActivity(), TocActivity_.class);
            fragmentSupport_ = fragment;
        }

        @Override
        public void startForResult(int requestCode) {
            if (fragmentSupport_!= null) {
                fragmentSupport_.startActivityForResult(intent, requestCode);
            } else {
                super.startForResult(requestCode);
            }
        }

    }

}
